// <auto-generated />
namespace BookingApp_v1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createPackageTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createPackageTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202409261717070_createPackageTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
